/**
 * A grocery and household catalogue for the live search demo.
 *
 * Everything here is invented product data — the point is the retrieval and
 * ranking code in ./parse.ts and ./rank.ts, which is real. `ctr` and `atc` are
 * synthetic demand priors standing in for what a real deployment learns from
 * click logs; they are labelled as such in the UI.
 *
 * Two rules when adding rows:
 *
 *  1. `diet` is a claim, not a tag. Only list what the product genuinely
 *     satisfies — the dietary signal is a hard filter in rank.ts, so a wrong
 *     entry here shows up as a wrong answer on the page. Dairy is
 *     `vegetarian`, never `vegan`; eggs are neither.
 *  2. A new `category` needs a matching entry in CATEGORY_TERMS in parse.ts,
 *     or nothing a visitor types will ever route to it.
 */

export type Unit = "l" | "ml" | "g" | "kg" | "pack";

export interface Product {
  id: string;
  title: string;
  brand: string;
  category: string;
  /** Extra searchable terms that aren't in the title. */
  tags: string[];
  size?: { value: number; unit: Unit };
  /** INR. */
  price: number;
  /** Dietary attributes this product genuinely satisfies. */
  diet: string[];
  /** Synthetic click-through prior, 0–1. */
  ctr: number;
  /** Synthetic add-to-cart prior, 0–1. */
  atc: number;
}

export const catalogue: Product[] = [
  // ---- milk & alternatives -------------------------------------------------
  {
    id: "p01",
    title: "Oat milk",
    brand: "Alpro",
    category: "milk alternative",
    tags: ["oat", "plant based", "barista"],
    size: { value: 1, unit: "l" },
    price: 189,
    diet: ["dairy-free", "lactose-free", "vegan"],
    ctr: 0.42,
    atc: 0.31,
  },
  {
    id: "p02",
    title: "Almond milk, unsweetened",
    brand: "Sofit",
    category: "milk alternative",
    tags: ["almond", "plant based", "nut"],
    size: { value: 1, unit: "l" },
    price: 165,
    diet: ["dairy-free", "lactose-free", "vegan", "sugar-free"],
    ctr: 0.36,
    atc: 0.24,
  },
  {
    id: "p03",
    title: "Soy milk",
    brand: "Staeta",
    category: "milk alternative",
    tags: ["soya", "plant based"],
    size: { value: 1, unit: "l" },
    price: 149,
    diet: ["dairy-free", "lactose-free", "vegan"],
    ctr: 0.28,
    atc: 0.19,
  },
  {
    id: "p04",
    title: "Full-cream milk",
    brand: "Amul",
    category: "milk",
    tags: ["dairy", "whole", "toned"],
    size: { value: 1, unit: "l" },
    price: 72,
    diet: ["vegetarian"],
    ctr: 0.61,
    atc: 0.48,
  },
  {
    id: "p05",
    title: "Toned milk",
    brand: "Mother Dairy",
    category: "milk",
    tags: ["dairy", "low fat"],
    size: { value: 500, unit: "ml" },
    price: 31,
    diet: ["vegetarian"],
    ctr: 0.55,
    atc: 0.44,
  },
  {
    id: "p06",
    title: "Lactose-free milk",
    brand: "Amul",
    category: "milk",
    tags: ["dairy", "digestive"],
    size: { value: 1, unit: "l" },
    price: 118,
    diet: ["lactose-free", "vegetarian"],
    ctr: 0.22,
    atc: 0.17,
  },
  {
    id: "p07",
    title: "Coconut milk",
    brand: "Dabur",
    category: "milk alternative",
    tags: ["coconut", "cooking", "plant based"],
    size: { value: 400, unit: "ml" },
    price: 96,
    diet: ["dairy-free", "lactose-free", "vegan"],
    ctr: 0.19,
    atc: 0.14,
  },
  {
    id: "p08",
    title: "Double-toned milk",
    brand: "Amul",
    category: "milk",
    tags: ["dairy", "skimmed", "low fat"],
    size: { value: 1, unit: "l" },
    price: 66,
    diet: ["vegetarian"],
    ctr: 0.34,
    atc: 0.27,
  },
  {
    id: "p09",
    title: "Buffalo milk",
    brand: "Gokul",
    category: "milk",
    tags: ["dairy", "full fat", "creamy"],
    size: { value: 1, unit: "l" },
    price: 84,
    diet: ["vegetarian"],
    ctr: 0.18,
    atc: 0.14,
  },
  {
    id: "p0a",
    title: "Rice milk",
    brand: "Nutrimix",
    category: "milk alternative",
    tags: ["rice", "plant based"],
    size: { value: 1, unit: "l" },
    price: 175,
    diet: ["dairy-free", "lactose-free", "vegan", "gluten-free"],
    ctr: 0.09,
    atc: 0.06,
  },
  {
    id: "p0b",
    title: "Cashew milk, barista",
    brand: "Sofit",
    category: "milk alternative",
    tags: ["cashew", "plant based", "nut", "barista"],
    size: { value: 1, unit: "l" },
    price: 210,
    diet: ["dairy-free", "lactose-free", "vegan"],
    ctr: 0.13,
    atc: 0.09,
  },
  {
    id: "p0c",
    title: "Condensed milk",
    brand: "Nestlé",
    category: "dairy",
    tags: ["milkmaid", "dessert", "baking", "sweet"],
    size: { value: 400, unit: "g" },
    price: 135,
    diet: ["vegetarian"],
    ctr: 0.25,
    atc: 0.2,
  },

  // ---- dairy ---------------------------------------------------------------
  {
    id: "p70",
    title: "Fresh curd",
    brand: "Mother Dairy",
    category: "dairy",
    tags: ["dahi", "yoghurt", "probiotic"],
    size: { value: 400, unit: "g" },
    price: 55,
    diet: ["vegetarian", "gluten-free"],
    ctr: 0.62,
    atc: 0.53,
  },
  {
    id: "p71",
    title: "Greek yoghurt, plain",
    brand: "Epigamia",
    category: "dairy",
    tags: ["yogurt", "high protein", "dahi"],
    size: { value: 400, unit: "g" },
    price: 150,
    diet: ["vegetarian", "gluten-free"],
    ctr: 0.38,
    atc: 0.29,
  },
  {
    id: "p72",
    title: "Paneer block",
    brand: "Amul",
    category: "dairy",
    tags: ["cottage cheese", "malai", "protein"],
    size: { value: 200, unit: "g" },
    price: 95,
    diet: ["vegetarian", "gluten-free"],
    ctr: 0.57,
    atc: 0.48,
  },
  {
    id: "p73",
    title: "Salted butter",
    brand: "Amul",
    category: "dairy",
    tags: ["makhan", "spread", "baking"],
    size: { value: 500, unit: "g" },
    price: 275,
    diet: ["vegetarian", "gluten-free"],
    ctr: 0.59,
    atc: 0.5,
  },
  {
    id: "p74",
    title: "Cheese slices",
    brand: "Britannia",
    category: "dairy",
    tags: ["processed cheese", "sandwich"],
    size: { value: 200, unit: "g" },
    price: 140,
    diet: ["vegetarian"],
    ctr: 0.44,
    atc: 0.36,
  },
  {
    id: "p75",
    title: "Mozzarella, shredded",
    brand: "Go",
    category: "dairy",
    tags: ["pizza cheese", "cheese"],
    size: { value: 200, unit: "g" },
    price: 185,
    diet: ["vegetarian", "gluten-free"],
    ctr: 0.33,
    atc: 0.26,
  },
  {
    id: "p76",
    title: "Cow ghee",
    brand: "Amul",
    category: "dairy",
    tags: ["clarified butter", "desi ghee"],
    size: { value: 1, unit: "l" },
    price: 650,
    diet: ["vegetarian", "gluten-free"],
    ctr: 0.47,
    atc: 0.4,
  },
  {
    id: "p77",
    title: "Fresh cream",
    brand: "Amul",
    category: "dairy",
    tags: ["malai", "whipping", "dessert"],
    size: { value: 250, unit: "ml" },
    price: 90,
    diet: ["vegetarian", "gluten-free"],
    ctr: 0.3,
    atc: 0.24,
  },
  {
    id: "p78",
    title: "Probiotic lassi, sweet",
    brand: "Mother Dairy",
    category: "dairy",
    tags: ["chaas", "yoghurt drink"],
    size: { value: 200, unit: "ml" },
    price: 25,
    diet: ["vegetarian", "gluten-free"],
    ctr: 0.36,
    atc: 0.3,
  },
  {
    id: "p79",
    title: "Vegan curd, coconut",
    brand: "Epigamia",
    category: "dairy",
    tags: ["dahi", "plant based", "coconut"],
    size: { value: 200, unit: "g" },
    price: 120,
    diet: ["vegan", "dairy-free", "lactose-free", "gluten-free"],
    ctr: 0.11,
    atc: 0.08,
  },

  // ---- eggs ----------------------------------------------------------------
  {
    id: "p80",
    title: "Farm eggs, brown",
    brand: "Eggoz",
    category: "eggs",
    tags: ["anda", "protein", "free range"],
    size: { value: 6, unit: "pack" },
    price: 90,
    diet: ["gluten-free"],
    ctr: 0.54,
    atc: 0.46,
  },
  {
    id: "p81",
    title: "White eggs, tray",
    brand: "Suguna",
    category: "eggs",
    tags: ["anda", "protein", "bulk"],
    size: { value: 30, unit: "pack" },
    price: 330,
    diet: ["gluten-free"],
    ctr: 0.41,
    atc: 0.35,
  },

  // ---- bread & bakery ------------------------------------------------------
  {
    id: "p10",
    title: "Whole wheat bread",
    brand: "Britannia",
    category: "bread",
    tags: ["atta", "loaf", "brown"],
    size: { value: 400, unit: "g" },
    price: 55,
    diet: ["vegetarian"],
    ctr: 0.47,
    atc: 0.39,
  },
  {
    id: "p11",
    title: "Multigrain bread",
    brand: "Harvest Gold",
    category: "bread",
    tags: ["seeds", "loaf", "brown"],
    size: { value: 400, unit: "g" },
    price: 68,
    diet: ["vegetarian"],
    ctr: 0.33,
    atc: 0.26,
  },
  {
    id: "p12",
    title: "Gluten-free bread",
    brand: "Nutrimix",
    category: "bread",
    tags: ["loaf", "celiac"],
    size: { value: 350, unit: "g" },
    price: 210,
    diet: ["gluten-free", "vegetarian"],
    ctr: 0.12,
    atc: 0.09,
  },
  {
    id: "p13",
    title: "Sourdough loaf",
    brand: "Theobroma",
    category: "bread",
    tags: ["artisan", "bakery"],
    size: { value: 500, unit: "g" },
    price: 240,
    diet: ["vegetarian"],
    ctr: 0.21,
    atc: 0.15,
  },
  {
    id: "p14",
    title: "White sandwich bread",
    brand: "Britannia",
    category: "bread",
    tags: ["loaf", "maida", "sandwich"],
    size: { value: 400, unit: "g" },
    price: 45,
    diet: ["vegetarian"],
    ctr: 0.5,
    atc: 0.43,
  },
  {
    id: "p15",
    title: "Burger buns",
    brand: "Harvest Gold",
    category: "bread",
    tags: ["bun", "pav", "bakery"],
    size: { value: 6, unit: "pack" },
    price: 50,
    diet: ["vegetarian"],
    ctr: 0.3,
    atc: 0.25,
  },
  {
    id: "p16",
    title: "Ladi pav",
    brand: "Modern",
    category: "bread",
    tags: ["bun", "pav bhaji", "bakery"],
    size: { value: 6, unit: "pack" },
    price: 40,
    diet: ["vegetarian"],
    ctr: 0.35,
    atc: 0.3,
  },
  {
    id: "p17",
    title: "Garlic breadsticks",
    brand: "Theobroma",
    category: "bread",
    tags: ["bakery", "sticks", "herb"],
    size: { value: 200, unit: "g" },
    price: 160,
    diet: ["vegetarian"],
    ctr: 0.15,
    atc: 0.11,
  },
  {
    id: "p18",
    title: "Brown rusk, elaichi",
    brand: "Britannia",
    category: "bread",
    tags: ["toast", "tea time", "bakery"],
    size: { value: 300, unit: "g" },
    price: 60,
    diet: ["vegetarian"],
    ctr: 0.27,
    atc: 0.22,
  },

  // ---- breakfast -----------------------------------------------------------
  {
    id: "p90",
    title: "Rolled oats",
    brand: "Quaker",
    category: "breakfast",
    tags: ["oats", "porridge", "cereal", "fibre"],
    size: { value: 1, unit: "kg" },
    price: 215,
    diet: ["vegan"],
    ctr: 0.52,
    atc: 0.44,
  },
  {
    id: "p91",
    title: "Corn flakes, original",
    brand: "Kellogg's",
    category: "breakfast",
    tags: ["cereal", "flakes"],
    size: { value: 475, unit: "g" },
    price: 240,
    diet: ["vegetarian"],
    ctr: 0.44,
    atc: 0.36,
  },
  {
    id: "p92",
    title: "Fruit & nut muesli",
    brand: "Bagrry's",
    category: "breakfast",
    tags: ["cereal", "granola", "oats"],
    size: { value: 700, unit: "g" },
    price: 420,
    diet: ["vegetarian"],
    ctr: 0.3,
    atc: 0.24,
  },
  {
    id: "p93",
    title: "Peanut butter, crunchy",
    brand: "Pintola",
    category: "breakfast",
    tags: ["spread", "protein", "nut butter"],
    size: { value: 1, unit: "kg" },
    price: 450,
    diet: ["vegan", "gluten-free"],
    ctr: 0.41,
    atc: 0.34,
  },
  {
    id: "p94",
    title: "Mixed fruit jam",
    brand: "Kissan",
    category: "breakfast",
    tags: ["spread", "preserve", "sweet"],
    size: { value: 700, unit: "g" },
    price: 210,
    diet: ["vegetarian", "gluten-free"],
    ctr: 0.38,
    atc: 0.31,
  },
  {
    id: "p95",
    title: "Raw forest honey",
    brand: "Dabur",
    category: "breakfast",
    tags: ["shahad", "sweetener", "natural"],
    size: { value: 1, unit: "kg" },
    price: 480,
    diet: ["vegetarian", "gluten-free"],
    ctr: 0.35,
    atc: 0.28,
  },
  {
    id: "p96",
    title: "Instant poha mix",
    brand: "MTR",
    category: "breakfast",
    tags: ["flattened rice", "ready mix"],
    size: { value: 80, unit: "g" },
    price: 45,
    diet: ["vegan", "gluten-free"],
    ctr: 0.19,
    atc: 0.15,
  },
  {
    id: "p97",
    title: "Chocolate health drink mix",
    brand: "Bournvita",
    category: "breakfast",
    tags: ["malt", "milk additive", "kids"],
    size: { value: 750, unit: "g" },
    price: 380,
    diet: ["vegetarian"],
    ctr: 0.4,
    atc: 0.33,
  },

  // ---- snacks --------------------------------------------------------------
  {
    id: "p20",
    title: "Salted potato chips",
    brand: "Lay's",
    category: "snacks",
    tags: ["crisps", "wafers", "namkeen"],
    size: { value: 90, unit: "g" },
    price: 30,
    diet: ["vegetarian"],
    ctr: 0.66,
    atc: 0.52,
  },
  {
    id: "p21",
    title: "Baked ragi chips",
    brand: "Yoga Bar",
    category: "snacks",
    tags: ["millet", "healthy", "baked"],
    size: { value: 60, unit: "g" },
    price: 85,
    diet: ["vegan", "gluten-free"],
    ctr: 0.18,
    atc: 0.13,
  },
  {
    id: "p22",
    title: "Roasted almonds",
    brand: "Happilo",
    category: "snacks",
    tags: ["nuts", "dry fruit", "protein"],
    size: { value: 200, unit: "g" },
    price: 340,
    diet: ["vegan", "gluten-free"],
    ctr: 0.39,
    atc: 0.3,
  },
  {
    id: "p23",
    title: "Dark chocolate 70%",
    brand: "Amul",
    category: "snacks",
    tags: ["cocoa", "bar", "sweet"],
    size: { value: 150, unit: "g" },
    price: 175,
    diet: ["vegetarian"],
    ctr: 0.44,
    atc: 0.35,
  },
  {
    id: "p24",
    title: "Sugar-free digestive biscuits",
    brand: "Sunfeast",
    category: "snacks",
    tags: ["cookies", "diabetic", "tea time"],
    size: { value: 250, unit: "g" },
    price: 90,
    diet: ["sugar-free", "vegetarian"],
    ctr: 0.26,
    atc: 0.2,
  },
  {
    id: "p25",
    title: "Protein bar, peanut butter",
    brand: "Yoga Bar",
    category: "snacks",
    tags: ["fitness", "gym", "bar"],
    size: { value: 6, unit: "pack" },
    price: 480,
    diet: ["vegetarian"],
    ctr: 0.31,
    atc: 0.23,
  },
  {
    id: "p26",
    title: "Aloo bhujia",
    brand: "Haldiram's",
    category: "snacks",
    tags: ["namkeen", "sev", "spicy"],
    size: { value: 400, unit: "g" },
    price: 110,
    diet: ["vegetarian"],
    ctr: 0.58,
    atc: 0.49,
  },
  {
    id: "p27",
    title: "Masala peanuts",
    brand: "Haldiram's",
    category: "snacks",
    tags: ["namkeen", "moongphali", "spicy"],
    size: { value: 200, unit: "g" },
    price: 65,
    diet: ["vegan", "gluten-free"],
    ctr: 0.42,
    atc: 0.35,
  },
  {
    id: "p28",
    title: "Marie biscuits",
    brand: "Britannia",
    category: "snacks",
    tags: ["cookies", "tea time", "light"],
    size: { value: 300, unit: "g" },
    price: 45,
    diet: ["vegetarian"],
    ctr: 0.5,
    atc: 0.44,
  },
  {
    id: "p29",
    title: "Choco-chip cookies",
    brand: "Unibic",
    category: "snacks",
    tags: ["biscuits", "sweet", "chocolate"],
    size: { value: 250, unit: "g" },
    price: 120,
    diet: ["vegetarian"],
    ctr: 0.37,
    atc: 0.3,
  },
  {
    id: "p2a",
    title: "Salted popcorn",
    brand: "Act II",
    category: "snacks",
    tags: ["microwave", "corn", "movie"],
    size: { value: 3, unit: "pack" },
    price: 90,
    diet: ["vegetarian", "gluten-free"],
    ctr: 0.29,
    atc: 0.24,
  },
  {
    id: "p2b",
    title: "Mixed dry fruits",
    brand: "Happilo",
    category: "snacks",
    tags: ["nuts", "raisins", "cashew", "dry fruit"],
    size: { value: 500, unit: "g" },
    price: 620,
    diet: ["vegan", "gluten-free"],
    ctr: 0.33,
    atc: 0.26,
  },
  {
    id: "p2c",
    title: "Makhana, roasted peri-peri",
    brand: "Farmley",
    category: "snacks",
    tags: ["fox nuts", "healthy", "baked"],
    size: { value: 100, unit: "g" },
    price: 150,
    diet: ["vegetarian", "gluten-free"],
    ctr: 0.21,
    atc: 0.16,
  },
  {
    id: "p2d",
    title: "Instant noodles, masala",
    brand: "Maggi",
    category: "snacks",
    tags: ["ready to eat", "2 minute", "noodles"],
    size: { value: 12, unit: "pack" },
    price: 168,
    diet: ["vegetarian"],
    ctr: 0.71,
    atc: 0.63,
  },
  {
    id: "p2e",
    title: "Sugar-free dark chocolate",
    brand: "Sugarfree",
    category: "snacks",
    tags: ["cocoa", "diabetic", "bar"],
    size: { value: 80, unit: "g" },
    price: 140,
    diet: ["sugar-free", "vegetarian"],
    ctr: 0.14,
    atc: 0.1,
  },

  // ---- produce -------------------------------------------------------------
  {
    id: "p30",
    title: "Bananas",
    brand: "Fresho",
    category: "produce",
    tags: ["fruit", "fresh", "kela"],
    size: { value: 1, unit: "kg" },
    price: 58,
    diet: ["vegan", "gluten-free"],
    ctr: 0.72,
    atc: 0.61,
  },
  {
    id: "p31",
    title: "Baby spinach",
    brand: "Fresho",
    category: "produce",
    tags: ["greens", "leafy", "palak", "salad"],
    size: { value: 200, unit: "g" },
    price: 45,
    diet: ["vegan", "gluten-free"],
    ctr: 0.29,
    atc: 0.22,
  },
  {
    id: "p32",
    title: "Avocado",
    brand: "Imported",
    category: "produce",
    tags: ["fruit", "fresh", "hass"],
    size: { value: 2, unit: "pack" },
    price: 320,
    diet: ["vegan", "gluten-free"],
    ctr: 0.35,
    atc: 0.24,
  },
  {
    id: "p33",
    title: "Roma tomatoes",
    brand: "Fresho",
    category: "produce",
    tags: ["vegetable", "fresh", "tamatar", "salad"],
    size: { value: 1, unit: "kg" },
    price: 42,
    diet: ["vegan", "gluten-free"],
    ctr: 0.58,
    atc: 0.49,
  },
  {
    id: "p34",
    title: "Organic baby carrots",
    brand: "24 Mantra",
    category: "produce",
    tags: ["vegetable", "fresh", "gajar"],
    size: { value: 500, unit: "g" },
    price: 110,
    diet: ["vegan", "gluten-free", "organic"],
    ctr: 0.24,
    atc: 0.18,
  },
  {
    id: "p35",
    title: "Onions",
    brand: "Fresho",
    category: "produce",
    tags: ["vegetable", "pyaz", "fresh"],
    size: { value: 2, unit: "kg" },
    price: 70,
    diet: ["vegan", "gluten-free"],
    ctr: 0.77,
    atc: 0.7,
  },
  {
    id: "p36",
    title: "Potatoes",
    brand: "Fresho",
    category: "produce",
    tags: ["vegetable", "aloo", "fresh"],
    size: { value: 2, unit: "kg" },
    price: 60,
    diet: ["vegan", "gluten-free"],
    ctr: 0.75,
    atc: 0.68,
  },
  {
    id: "p37",
    title: "Organic cauliflower",
    brand: "24 Mantra",
    category: "produce",
    tags: ["vegetable", "gobi", "fresh"],
    size: { value: 1, unit: "kg" },
    price: 95,
    diet: ["vegan", "gluten-free", "organic"],
    ctr: 0.26,
    atc: 0.2,
  },
  {
    id: "p38",
    title: "Green capsicum",
    brand: "Fresho",
    category: "produce",
    tags: ["vegetable", "shimla mirch", "fresh"],
    size: { value: 500, unit: "g" },
    price: 55,
    diet: ["vegan", "gluten-free"],
    ctr: 0.31,
    atc: 0.25,
  },
  {
    id: "p39",
    title: "Lady finger",
    brand: "Fresho",
    category: "produce",
    tags: ["vegetable", "bhindi", "okra", "fresh"],
    size: { value: 500, unit: "g" },
    price: 40,
    diet: ["vegan", "gluten-free"],
    ctr: 0.34,
    atc: 0.28,
  },
  {
    id: "p3a",
    title: "Coriander leaves",
    brand: "Fresho",
    category: "produce",
    tags: ["herb", "dhania", "garnish", "fresh"],
    size: { value: 100, unit: "g" },
    price: 15,
    diet: ["vegan", "gluten-free"],
    ctr: 0.46,
    atc: 0.4,
  },
  {
    id: "p3b",
    title: "Ginger",
    brand: "Fresho",
    category: "produce",
    tags: ["adrak", "aromatic", "fresh"],
    size: { value: 250, unit: "g" },
    price: 45,
    diet: ["vegan", "gluten-free"],
    ctr: 0.43,
    atc: 0.37,
  },
  {
    id: "p3c",
    title: "Garlic",
    brand: "Fresho",
    category: "produce",
    tags: ["lehsun", "aromatic", "fresh"],
    size: { value: 250, unit: "g" },
    price: 60,
    diet: ["vegan", "gluten-free"],
    ctr: 0.45,
    atc: 0.39,
  },
  {
    id: "p3d",
    title: "Apples, Shimla",
    brand: "Fresho",
    category: "produce",
    tags: ["fruit", "seb", "fresh"],
    size: { value: 1, unit: "kg" },
    price: 180,
    diet: ["vegan", "gluten-free"],
    ctr: 0.52,
    atc: 0.43,
  },
  {
    id: "p3e",
    title: "Alphonso mangoes",
    brand: "Fresho",
    category: "produce",
    tags: ["fruit", "aam", "seasonal", "fresh"],
    size: { value: 1, unit: "kg" },
    price: 650,
    diet: ["vegan", "gluten-free"],
    ctr: 0.4,
    atc: 0.3,
  },
  {
    id: "p3f",
    title: "Seedless grapes",
    brand: "Fresho",
    category: "produce",
    tags: ["fruit", "angoor", "fresh"],
    size: { value: 500, unit: "g" },
    price: 95,
    diet: ["vegan", "gluten-free"],
    ctr: 0.37,
    atc: 0.3,
  },
  {
    id: "p3g",
    title: "Organic baby spinach",
    brand: "24 Mantra",
    category: "produce",
    tags: ["greens", "leafy", "palak", "salad"],
    size: { value: 200, unit: "g" },
    price: 80,
    diet: ["vegan", "gluten-free", "organic"],
    ctr: 0.17,
    atc: 0.13,
  },
  {
    id: "p3h",
    title: "Lemons",
    brand: "Fresho",
    category: "produce",
    tags: ["fruit", "nimbu", "fresh"],
    size: { value: 500, unit: "g" },
    price: 50,
    diet: ["vegan", "gluten-free"],
    ctr: 0.48,
    atc: 0.42,
  },
  {
    id: "p3i",
    title: "Cucumber",
    brand: "Fresho",
    category: "produce",
    tags: ["vegetable", "kheera", "salad", "fresh"],
    size: { value: 500, unit: "g" },
    price: 35,
    diet: ["vegan", "gluten-free"],
    ctr: 0.39,
    atc: 0.33,
  },
  {
    id: "p3j",
    title: "Organic mixed salad leaves",
    brand: "24 Mantra",
    category: "produce",
    tags: ["greens", "lettuce", "salad", "leafy"],
    size: { value: 150, unit: "g" },
    price: 140,
    diet: ["vegan", "gluten-free", "organic"],
    ctr: 0.15,
    atc: 0.11,
  },

  // ---- staples -------------------------------------------------------------
  {
    id: "p40",
    title: "Basmati rice",
    brand: "India Gate",
    category: "staples",
    tags: ["chawal", "grain", "long grain"],
    size: { value: 5, unit: "kg" },
    price: 690,
    diet: ["vegan", "gluten-free"],
    ctr: 0.51,
    atc: 0.42,
  },
  {
    id: "p41",
    title: "Whole wheat atta",
    brand: "Aashirvaad",
    category: "staples",
    tags: ["flour", "chakki", "roti"],
    size: { value: 5, unit: "kg" },
    price: 285,
    diet: ["vegetarian"],
    ctr: 0.63,
    atc: 0.55,
  },
  {
    id: "p42",
    title: "Toor dal",
    brand: "Tata Sampann",
    category: "staples",
    tags: ["lentil", "pulses", "arhar"],
    size: { value: 1, unit: "kg" },
    price: 178,
    diet: ["vegan", "gluten-free"],
    ctr: 0.49,
    atc: 0.41,
  },
  {
    id: "p43",
    title: "Cold-pressed mustard oil",
    brand: "Fortune",
    category: "staples",
    tags: ["cooking oil", "sarson", "kachi ghani"],
    size: { value: 1, unit: "l" },
    price: 195,
    diet: ["vegan", "gluten-free"],
    ctr: 0.37,
    atc: 0.3,
  },
  {
    id: "p44",
    title: "Organic jaggery powder",
    brand: "24 Mantra",
    category: "staples",
    tags: ["gur", "sweetener", "unrefined"],
    size: { value: 500, unit: "g" },
    price: 130,
    diet: ["vegan", "gluten-free", "organic"],
    ctr: 0.16,
    atc: 0.12,
  },
  {
    id: "p45",
    title: "Sona masoori rice",
    brand: "Daawat",
    category: "staples",
    tags: ["chawal", "grain", "everyday"],
    size: { value: 10, unit: "kg" },
    price: 720,
    diet: ["vegan", "gluten-free"],
    ctr: 0.44,
    atc: 0.38,
  },
  {
    id: "p46",
    title: "Moong dal, yellow",
    brand: "Tata Sampann",
    category: "staples",
    tags: ["lentil", "pulses", "split"],
    size: { value: 1, unit: "kg" },
    price: 165,
    diet: ["vegan", "gluten-free"],
    ctr: 0.4,
    atc: 0.34,
  },
  {
    id: "p47",
    title: "Chana dal",
    brand: "Tata Sampann",
    category: "staples",
    tags: ["lentil", "pulses", "bengal gram"],
    size: { value: 1, unit: "kg" },
    price: 120,
    diet: ["vegan", "gluten-free"],
    ctr: 0.36,
    atc: 0.31,
  },
  {
    id: "p48",
    title: "Rajma, chitra",
    brand: "24 Mantra",
    category: "staples",
    tags: ["kidney beans", "pulses", "organic"],
    size: { value: 500, unit: "g" },
    price: 140,
    diet: ["vegan", "gluten-free", "organic"],
    ctr: 0.24,
    atc: 0.19,
  },
  {
    id: "p49",
    title: "Kabuli chana",
    brand: "Tata Sampann",
    category: "staples",
    tags: ["chickpeas", "pulses", "chole"],
    size: { value: 1, unit: "kg" },
    price: 150,
    diet: ["vegan", "gluten-free"],
    ctr: 0.33,
    atc: 0.28,
  },
  {
    id: "p4a",
    title: "Sunflower refined oil",
    brand: "Fortune",
    category: "staples",
    tags: ["cooking oil", "refined", "frying"],
    size: { value: 5, unit: "l" },
    price: 790,
    diet: ["vegan", "gluten-free"],
    ctr: 0.5,
    atc: 0.44,
  },
  {
    id: "p4b",
    title: "Extra virgin olive oil",
    brand: "Figaro",
    category: "staples",
    tags: ["cooking oil", "salad", "mediterranean"],
    size: { value: 1, unit: "l" },
    price: 950,
    diet: ["vegan", "gluten-free"],
    ctr: 0.22,
    atc: 0.16,
  },
  {
    id: "p4c",
    title: "Besan, gram flour",
    brand: "Rajdhani",
    category: "staples",
    tags: ["flour", "chickpea", "pakora"],
    size: { value: 1, unit: "kg" },
    price: 95,
    diet: ["vegan", "gluten-free"],
    ctr: 0.3,
    atc: 0.26,
  },
  {
    id: "p4d",
    title: "Sooji, rava",
    brand: "Rajdhani",
    category: "staples",
    tags: ["semolina", "upma", "flour"],
    size: { value: 1, unit: "kg" },
    price: 70,
    diet: ["vegetarian"],
    ctr: 0.27,
    atc: 0.23,
  },
  {
    id: "p4e",
    title: "Refined sugar",
    brand: "Madhur",
    category: "staples",
    tags: ["cheeni", "sweetener"],
    size: { value: 5, unit: "kg" },
    price: 290,
    diet: ["vegan", "gluten-free"],
    ctr: 0.54,
    atc: 0.48,
  },
  {
    id: "p4f",
    title: "Iodised salt",
    brand: "Tata",
    category: "staples",
    tags: ["namak", "seasoning"],
    size: { value: 1, unit: "kg" },
    price: 28,
    diet: ["vegan", "gluten-free"],
    ctr: 0.7,
    atc: 0.64,
  },
  {
    id: "p4g",
    title: "Poha, thick",
    brand: "Rajdhani",
    category: "staples",
    tags: ["flattened rice", "breakfast", "chawal"],
    size: { value: 1, unit: "kg" },
    price: 75,
    diet: ["vegan", "gluten-free"],
    ctr: 0.26,
    atc: 0.22,
  },
  {
    id: "p4h",
    title: "Organic brown rice",
    brand: "24 Mantra",
    category: "staples",
    tags: ["chawal", "grain", "whole grain"],
    size: { value: 1, unit: "kg" },
    price: 185,
    diet: ["vegan", "gluten-free", "organic"],
    ctr: 0.19,
    atc: 0.15,
  },
  {
    id: "p4i",
    title: "Vermicelli, roasted",
    brand: "Bambino",
    category: "staples",
    tags: ["seviyan", "noodles", "kheer"],
    size: { value: 900, unit: "g" },
    price: 110,
    diet: ["vegetarian"],
    ctr: 0.18,
    atc: 0.15,
  },

  // ---- spices --------------------------------------------------------------
  {
    id: "pa0",
    title: "Turmeric powder",
    brand: "Everest",
    category: "spices",
    tags: ["haldi", "masala", "seasoning"],
    size: { value: 200, unit: "g" },
    price: 75,
    diet: ["vegan", "gluten-free"],
    ctr: 0.47,
    atc: 0.41,
  },
  {
    id: "pa1",
    title: "Red chilli powder",
    brand: "Everest",
    category: "spices",
    tags: ["lal mirch", "masala", "spicy"],
    size: { value: 200, unit: "g" },
    price: 95,
    diet: ["vegan", "gluten-free"],
    ctr: 0.46,
    atc: 0.4,
  },
  {
    id: "pa2",
    title: "Coriander powder",
    brand: "Everest",
    category: "spices",
    tags: ["dhania", "masala", "seasoning"],
    size: { value: 200, unit: "g" },
    price: 70,
    diet: ["vegan", "gluten-free"],
    ctr: 0.38,
    atc: 0.33,
  },
  {
    id: "pa3",
    title: "Garam masala",
    brand: "MDH",
    category: "spices",
    tags: ["masala", "blend", "seasoning"],
    size: { value: 100, unit: "g" },
    price: 85,
    diet: ["vegan", "gluten-free"],
    ctr: 0.44,
    atc: 0.38,
  },
  {
    id: "pa4",
    title: "Cumin seeds",
    brand: "Tata Sampann",
    category: "spices",
    tags: ["jeera", "whole spice", "tadka"],
    size: { value: 200, unit: "g" },
    price: 120,
    diet: ["vegan", "gluten-free"],
    ctr: 0.4,
    atc: 0.35,
  },
  {
    id: "pa5",
    title: "Organic black pepper",
    brand: "24 Mantra",
    category: "spices",
    tags: ["kali mirch", "whole spice", "seasoning"],
    size: { value: 100, unit: "g" },
    price: 180,
    diet: ["vegan", "gluten-free", "organic"],
    ctr: 0.21,
    atc: 0.16,
  },
  {
    id: "pa6",
    title: "Mustard seeds",
    brand: "Catch",
    category: "spices",
    tags: ["rai", "whole spice", "tadka"],
    size: { value: 100, unit: "g" },
    price: 40,
    diet: ["vegan", "gluten-free"],
    ctr: 0.26,
    atc: 0.22,
  },
  {
    id: "pa7",
    title: "Chai masala",
    brand: "Everest",
    category: "spices",
    tags: ["tea masala", "blend", "aromatic"],
    size: { value: 50, unit: "g" },
    price: 55,
    diet: ["vegan", "gluten-free"],
    ctr: 0.19,
    atc: 0.15,
  },

  // ---- condiments ----------------------------------------------------------
  {
    id: "pb0",
    title: "Tomato ketchup",
    brand: "Kissan",
    category: "condiments",
    tags: ["sauce", "tamatar", "dip"],
    size: { value: 1, unit: "kg" },
    price: 150,
    diet: ["vegetarian", "gluten-free"],
    ctr: 0.52,
    atc: 0.45,
  },
  {
    id: "pb1",
    title: "Veg mayonnaise",
    brand: "Veeba",
    category: "condiments",
    tags: ["sauce", "dip", "spread"],
    size: { value: 875, unit: "g" },
    price: 210,
    diet: ["vegetarian"],
    ctr: 0.39,
    atc: 0.33,
  },
  {
    id: "pb2",
    title: "Soy sauce",
    brand: "Ching's",
    category: "condiments",
    tags: ["sauce", "chinese", "umami"],
    size: { value: 200, unit: "ml" },
    price: 75,
    diet: ["vegan"],
    ctr: 0.28,
    atc: 0.23,
  },
  {
    id: "pb3",
    title: "Mango pickle",
    brand: "Mother's Recipe",
    category: "condiments",
    tags: ["achar", "aam", "spicy"],
    size: { value: 400, unit: "g" },
    price: 130,
    diet: ["vegan", "gluten-free"],
    ctr: 0.34,
    atc: 0.29,
  },
  {
    id: "pb4",
    title: "Mint coriander chutney",
    brand: "Veeba",
    category: "condiments",
    tags: ["dip", "hari chutney", "sauce"],
    size: { value: 250, unit: "g" },
    price: 95,
    diet: ["vegan", "gluten-free"],
    ctr: 0.2,
    atc: 0.16,
  },
  {
    id: "pb5",
    title: "Apple cider vinegar",
    brand: "Dabur",
    category: "condiments",
    tags: ["vinegar", "sirka", "health"],
    size: { value: 500, unit: "ml" },
    price: 190,
    diet: ["vegan", "gluten-free"],
    ctr: 0.23,
    atc: 0.17,
  },
  {
    id: "pb6",
    title: "Peri-peri seasoning",
    brand: "Veeba",
    category: "condiments",
    tags: ["sauce", "spicy", "dip"],
    size: { value: 300, unit: "g" },
    price: 120,
    diet: ["vegetarian"],
    ctr: 0.17,
    atc: 0.13,
  },

  // ---- frozen --------------------------------------------------------------
  {
    id: "pc0",
    title: "Frozen green peas",
    brand: "Safal",
    category: "frozen",
    tags: ["matar", "vegetable", "freezer"],
    size: { value: 500, unit: "g" },
    price: 95,
    diet: ["vegan", "gluten-free"],
    ctr: 0.48,
    atc: 0.42,
  },
  {
    id: "pc1",
    title: "Frozen french fries",
    brand: "McCain",
    category: "frozen",
    tags: ["aloo", "potato", "freezer", "snack"],
    size: { value: 750, unit: "g" },
    price: 185,
    diet: ["vegan"],
    ctr: 0.44,
    atc: 0.37,
  },
  {
    id: "pc2",
    title: "Frozen malabar paratha",
    brand: "ID",
    category: "frozen",
    tags: ["paratha", "flatbread", "freezer"],
    size: { value: 5, unit: "pack" },
    price: 140,
    diet: ["vegetarian"],
    ctr: 0.36,
    atc: 0.31,
  },
  {
    id: "pc3",
    title: "Vanilla ice cream tub",
    brand: "Amul",
    category: "frozen",
    tags: ["dessert", "freezer", "sweet"],
    size: { value: 1, unit: "l" },
    price: 280,
    diet: ["vegetarian"],
    ctr: 0.42,
    atc: 0.35,
  },
  {
    id: "pc4",
    title: "Frozen sweet corn",
    brand: "Safal",
    category: "frozen",
    tags: ["makai", "vegetable", "freezer"],
    size: { value: 500, unit: "g" },
    price: 110,
    diet: ["vegan", "gluten-free"],
    ctr: 0.25,
    atc: 0.2,
  },

  // ---- beverages -----------------------------------------------------------
  {
    id: "p50",
    title: "Assam breakfast tea",
    brand: "Tetley",
    category: "beverages",
    tags: ["chai", "black tea", "leaves"],
    size: { value: 250, unit: "g" },
    price: 165,
    diet: ["vegan", "gluten-free"],
    ctr: 0.45,
    atc: 0.36,
  },
  {
    id: "p51",
    title: "Cold brew coffee concentrate",
    brand: "Sleepy Owl",
    category: "beverages",
    tags: ["coffee", "caffeine", "iced"],
    size: { value: 200, unit: "ml" },
    price: 299,
    diet: ["vegan"],
    ctr: 0.34,
    atc: 0.25,
  },
  {
    id: "p52",
    title: "Sparkling water, lime",
    brand: "Bisleri",
    category: "beverages",
    tags: ["soda", "fizzy", "carbonated"],
    size: { value: 750, unit: "ml" },
    price: 60,
    diet: ["vegan", "sugar-free", "gluten-free"],
    ctr: 0.27,
    atc: 0.19,
  },
  {
    id: "p53",
    title: "Orange juice, no added sugar",
    brand: "Real",
    category: "beverages",
    tags: ["fruit juice", "citrus"],
    size: { value: 1, unit: "l" },
    price: 135,
    diet: ["vegan", "sugar-free"],
    ctr: 0.4,
    atc: 0.32,
  },
  {
    id: "p54",
    title: "Masala chai tea bags",
    brand: "Tata Tea",
    category: "beverages",
    tags: ["chai", "tea bags", "spiced"],
    size: { value: 50, unit: "pack" },
    price: 180,
    diet: ["vegan", "gluten-free"],
    ctr: 0.38,
    atc: 0.32,
  },
  {
    id: "p55",
    title: "Instant coffee powder",
    brand: "Nescafé",
    category: "beverages",
    tags: ["coffee", "caffeine", "classic"],
    size: { value: 200, unit: "g" },
    price: 610,
    diet: ["vegetarian", "gluten-free"],
    ctr: 0.47,
    atc: 0.4,
  },
  {
    id: "p56",
    title: "Green tea bags",
    brand: "Lipton",
    category: "beverages",
    tags: ["tea", "antioxidant", "light"],
    size: { value: 100, unit: "pack" },
    price: 350,
    diet: ["vegan", "gluten-free"],
    ctr: 0.3,
    atc: 0.24,
  },
  {
    id: "p57",
    title: "Packaged drinking water",
    brand: "Bisleri",
    category: "beverages",
    tags: ["water", "mineral", "bottle"],
    size: { value: 20, unit: "l" },
    price: 90,
    diet: ["vegan", "sugar-free", "gluten-free"],
    ctr: 0.6,
    atc: 0.55,
  },
  {
    id: "p58",
    title: "Cola, no sugar",
    brand: "Coca-Cola",
    category: "beverages",
    tags: ["soft drink", "fizzy", "diet", "soda"],
    size: { value: 750, unit: "ml" },
    price: 45,
    diet: ["vegan", "sugar-free"],
    ctr: 0.5,
    atc: 0.44,
  },
  {
    id: "p59",
    title: "Tender coconut water",
    brand: "Cocofly",
    category: "beverages",
    tags: ["nariyal pani", "natural", "hydration"],
    size: { value: 200, unit: "ml" },
    price: 50,
    diet: ["vegan", "gluten-free", "sugar-free"],
    ctr: 0.26,
    atc: 0.21,
  },
  {
    id: "p5a",
    title: "Rose milkshake",
    brand: "Amul",
    category: "beverages",
    tags: ["milk drink", "flavoured", "sweet"],
    size: { value: 180, unit: "ml" },
    price: 30,
    diet: ["vegetarian", "gluten-free"],
    ctr: 0.22,
    atc: 0.18,
  },

  // ---- household -----------------------------------------------------------
  {
    id: "p60",
    title: "Dishwash liquid, lemon",
    brand: "Vim",
    category: "household",
    tags: ["cleaning", "utensil", "detergent", "bartan"],
    size: { value: 750, unit: "ml" },
    price: 145,
    diet: [],
    ctr: 0.53,
    atc: 0.45,
  },
  {
    id: "p61",
    title: "Laundry detergent powder",
    brand: "Surf Excel",
    category: "household",
    tags: ["washing", "clothes", "kapda"],
    size: { value: 2, unit: "kg" },
    price: 420,
    diet: [],
    ctr: 0.48,
    atc: 0.4,
  },
  {
    id: "p62",
    title: "Kitchen paper towels",
    brand: "Origami",
    category: "household",
    tags: ["tissue", "roll", "cleaning"],
    size: { value: 4, unit: "pack" },
    price: 199,
    diet: [],
    ctr: 0.3,
    atc: 0.24,
  },
  {
    id: "p63",
    title: "Dishwash bar",
    brand: "Vim",
    category: "household",
    tags: ["cleaning", "utensil", "bartan", "soap"],
    size: { value: 4, unit: "pack" },
    price: 60,
    diet: [],
    ctr: 0.45,
    atc: 0.4,
  },
  {
    id: "p64",
    title: "Liquid laundry detergent",
    brand: "Ariel",
    category: "household",
    tags: ["washing", "clothes", "front load"],
    size: { value: 2, unit: "l" },
    price: 590,
    diet: [],
    ctr: 0.35,
    atc: 0.29,
  },
  {
    id: "p65",
    title: "Floor cleaner, citrus",
    brand: "Lizol",
    category: "household",
    tags: ["cleaning", "disinfectant", "phenyl", "pocha"],
    size: { value: 2, unit: "l" },
    price: 380,
    diet: [],
    ctr: 0.5,
    atc: 0.43,
  },
  {
    id: "p66",
    title: "Toilet cleaner",
    brand: "Harpic",
    category: "household",
    tags: ["cleaning", "bathroom", "disinfectant"],
    size: { value: 1, unit: "l" },
    price: 195,
    diet: [],
    ctr: 0.52,
    atc: 0.46,
  },
  {
    id: "p67",
    title: "Glass cleaner spray",
    brand: "Colin",
    category: "household",
    tags: ["cleaning", "window", "spray"],
    size: { value: 500, unit: "ml" },
    price: 110,
    diet: [],
    ctr: 0.33,
    atc: 0.28,
  },
  {
    id: "p68",
    title: "Garbage bags, medium",
    brand: "Ezee",
    category: "household",
    tags: ["bin bags", "dustbin", "kachra"],
    size: { value: 30, unit: "pack" },
    price: 140,
    diet: [],
    ctr: 0.41,
    atc: 0.36,
  },
  {
    id: "p69",
    title: "Aluminium foil roll",
    brand: "Freshwrapp",
    category: "household",
    tags: ["kitchen", "wrap", "foil"],
    size: { value: 72, unit: "pack" },
    price: 160,
    diet: [],
    ctr: 0.29,
    atc: 0.24,
  },
  {
    id: "p6a",
    title: "Cling film wrap",
    brand: "Freshwrapp",
    category: "household",
    tags: ["kitchen", "wrap", "plastic"],
    size: { value: 30, unit: "pack" },
    price: 120,
    diet: [],
    ctr: 0.2,
    atc: 0.16,
  },
  {
    id: "p6b",
    title: "Scrub pads, pack of 6",
    brand: "Scotch-Brite",
    category: "household",
    tags: ["cleaning", "utensil", "sponge"],
    size: { value: 6, unit: "pack" },
    price: 90,
    diet: [],
    ctr: 0.38,
    atc: 0.33,
  },
  {
    id: "p6c",
    title: "Microfibre cleaning cloth",
    brand: "Scotch-Brite",
    category: "household",
    tags: ["cleaning", "duster", "wipe"],
    size: { value: 3, unit: "pack" },
    price: 180,
    diet: [],
    ctr: 0.22,
    atc: 0.18,
  },
  {
    id: "p6d",
    title: "Spin mop with bucket",
    brand: "Spotzero",
    category: "household",
    tags: ["cleaning", "pocha", "floor"],
    price: 1250,
    diet: [],
    ctr: 0.18,
    atc: 0.12,
  },
  {
    id: "p6e",
    title: "Mosquito repellent refill",
    brand: "Good Knight",
    category: "household",
    tags: ["pest", "machhar", "liquid"],
    size: { value: 45, unit: "ml" },
    price: 85,
    diet: [],
    ctr: 0.44,
    atc: 0.39,
  },
  {
    id: "p6f",
    title: "Cockroach killer gel",
    brand: "Hit",
    category: "household",
    tags: ["pest", "insect", "spray"],
    size: { value: 20, unit: "g" },
    price: 210,
    diet: [],
    ctr: 0.24,
    atc: 0.2,
  },
  {
    id: "p6g",
    title: "Air freshener, lavender",
    brand: "Godrej Aer",
    category: "household",
    tags: ["room spray", "fragrance", "home"],
    size: { value: 220, unit: "ml" },
    price: 225,
    diet: [],
    ctr: 0.27,
    atc: 0.22,
  },
  {
    id: "p6h",
    title: "Naphthalene balls",
    brand: "Maxo",
    category: "household",
    tags: ["wardrobe", "moth", "freshener"],
    size: { value: 200, unit: "g" },
    price: 70,
    diet: [],
    ctr: 0.14,
    atc: 0.11,
  },
  {
    id: "p6i",
    title: "Fabric conditioner, rose",
    brand: "Comfort",
    category: "household",
    tags: ["washing", "clothes", "softener"],
    size: { value: 860, unit: "ml" },
    price: 245,
    diet: [],
    ctr: 0.26,
    atc: 0.21,
  },
  {
    id: "p6j",
    title: "Bathroom cleaning brush",
    brand: "Gala",
    category: "household",
    tags: ["cleaning", "toilet", "brush"],
    price: 150,
    diet: [],
    ctr: 0.16,
    atc: 0.13,
  },
  {
    id: "p6k",
    title: "Matchbox, pack of 10",
    brand: "Homelite",
    category: "household",
    tags: ["kitchen", "fire", "essentials"],
    size: { value: 10, unit: "pack" },
    price: 20,
    diet: [],
    ctr: 0.31,
    atc: 0.28,
  },
  {
    id: "p6l",
    title: "LED bulb, 9W cool white",
    brand: "Philips",
    category: "household",
    tags: ["lighting", "bulb", "electrical"],
    size: { value: 2, unit: "pack" },
    price: 240,
    diet: [],
    ctr: 0.29,
    atc: 0.24,
  },

  // ---- personal care -------------------------------------------------------
  {
    id: "pd0",
    title: "Bathing soap, sandal",
    brand: "Mysore Sandal",
    category: "personal care",
    tags: ["soap", "bath", "fragrance"],
    size: { value: 4, unit: "pack" },
    price: 220,
    diet: [],
    ctr: 0.42,
    atc: 0.36,
  },
  {
    id: "pd1",
    title: "Anti-dandruff shampoo",
    brand: "Head & Shoulders",
    category: "personal care",
    tags: ["hair", "shampoo", "scalp"],
    size: { value: 650, unit: "ml" },
    price: 560,
    diet: [],
    ctr: 0.37,
    atc: 0.3,
  },
  {
    id: "pd2",
    title: "Toothpaste, whitening",
    brand: "Colgate",
    category: "personal care",
    tags: ["dental", "brush", "oral"],
    size: { value: 200, unit: "g" },
    price: 135,
    diet: [],
    ctr: 0.55,
    atc: 0.48,
  },
  {
    id: "pd3",
    title: "Handwash refill, aloe",
    brand: "Dettol",
    category: "personal care",
    tags: ["soap", "hygiene", "liquid"],
    size: { value: 1500, unit: "ml" },
    price: 280,
    diet: [],
    ctr: 0.4,
    atc: 0.35,
  },
  {
    id: "pd4",
    title: "Hand sanitiser",
    brand: "Dettol",
    category: "personal care",
    tags: ["hygiene", "alcohol", "gel"],
    size: { value: 500, unit: "ml" },
    price: 180,
    diet: [],
    ctr: 0.21,
    atc: 0.17,
  },
  {
    id: "pd5",
    title: "Deodorant spray",
    brand: "Nivea",
    category: "personal care",
    tags: ["body spray", "fragrance", "roll on"],
    size: { value: 150, unit: "ml" },
    price: 260,
    diet: [],
    ctr: 0.28,
    atc: 0.23,
  },
  {
    id: "pd6",
    title: "Coconut hair oil",
    brand: "Parachute",
    category: "personal care",
    tags: ["hair", "oil", "nariyal"],
    size: { value: 600, unit: "ml" },
    price: 290,
    diet: [],
    ctr: 0.39,
    atc: 0.34,
  },
  {
    id: "pd7",
    title: "Sanitary pads, XL",
    brand: "Whisper",
    category: "personal care",
    tags: ["feminine hygiene", "napkin"],
    size: { value: 30, unit: "pack" },
    price: 330,
    diet: [],
    ctr: 0.33,
    atc: 0.29,
  },
  {
    id: "pd8",
    title: "Toilet paper rolls",
    brand: "Origami",
    category: "personal care",
    tags: ["tissue", "bathroom", "roll"],
    size: { value: 6, unit: "pack" },
    price: 240,
    diet: [],
    ctr: 0.3,
    atc: 0.25,
  },

  // ---- baby ----------------------------------------------------------------
  {
    id: "pe0",
    title: "Baby diapers, pants M",
    brand: "Pampers",
    category: "baby",
    tags: ["nappy", "infant", "toddler"],
    size: { value: 62, unit: "pack" },
    price: 950,
    diet: [],
    ctr: 0.36,
    atc: 0.31,
  },
  {
    id: "pe1",
    title: "Baby wipes, fragrance-free",
    brand: "Himalaya",
    category: "baby",
    tags: ["wipes", "infant", "gentle"],
    size: { value: 72, unit: "pack" },
    price: 190,
    diet: [],
    ctr: 0.3,
    atc: 0.26,
  },
  {
    id: "pe2",
    title: "Baby cereal, rice",
    brand: "Nestlé Cerelac",
    category: "baby",
    tags: ["infant food", "porridge", "weaning"],
    size: { value: 300, unit: "g" },
    price: 285,
    diet: ["vegetarian"],
    ctr: 0.24,
    atc: 0.2,
  },

  // ---- pet -----------------------------------------------------------------
  {
    id: "pf0",
    title: "Adult dog food, chicken",
    brand: "Pedigree",
    category: "pet",
    tags: ["dog", "kibble", "pet food"],
    size: { value: 3, unit: "kg" },
    price: 780,
    diet: [],
    ctr: 0.27,
    atc: 0.23,
  },
  {
    id: "pf1",
    title: "Cat litter, clumping",
    brand: "Drools",
    category: "pet",
    tags: ["cat", "litter", "pet care"],
    size: { value: 5, unit: "kg" },
    price: 650,
    diet: [],
    ctr: 0.17,
    atc: 0.14,
  },

  // ---- the easter egg ------------------------------------------------------
  // Indexed like everything else. It only surfaces when the query actually
  // matches it — hardcoding it to rank #1 would make the whole demo a lie.
  {
    id: "me",
    title: "Abhinav Tyagi",
    brand: "Backend & Search Engineer",
    category: "engineer",
    tags: [
      "abhinav",
      "tyagi",
      "search",
      "relevance",
      "ranking",
      "elasticsearch",
      "learning to rank",
      "ltr",
      "backend",
      "java",
      "hire",
      "engineer",
      "who built this",
      "recruiter",
    ],
    price: 0,
    diet: [],
    ctr: 0.99,
    atc: 0.87,
  },
];
